import fs from 'fs';

// Generated by https://quicktype.io

interface Feature {
    type:       string;
    id:         number;
    geometry:   Geometry;
    properties: { [key: string]: number | null };
}

interface Geometry {
    type:        string;
    coordinates: Array<Array<number[]>>;
}

interface newFeature {
    type:       string;
    geometry:   Geometry;
    properties: { [key: string]: number };
}


const rawGeojson: { type: 'FeatureCollection', features: Feature[] } = JSON.parse(fs.readFileSync('../data-input/Homestead_Hexbins.json', 'utf-8'));

const fullfeatures: newFeature[] = rawGeojson.features.map(d => {
    const yearproperties: { [key: string]: number } = {};
    Object.keys(d.properties).forEach(key => {
        if (key.startsWith('SUM_c')) {
            const year = key.substr(6, 4);
            yearproperties[`y${year}`] = (d.properties[key]) ? d.properties[key] : 0;
        }
    });

    // add them all up to aggregate by year
    const properties: { [key: string]: number } = {};
    Object.keys(yearproperties).forEach(key => {
        const sum: number = Object.keys(properties)
            .filter(key1 => key1 <= key)
            .reduce((acc, currKey) => acc + yearproperties[currKey], 0);
        properties[key] = sum;
    });
    return {
        type: d.type,
        geometry: d.geometry,
        properties, 
    }
});

// filter out hexbins that don't have any data
const features = fullfeatures.filter(d => d.properties.y1911 > 0);

const json = {
    type: 'FeatureCollection',
    features,
};

console.log(JSON.stringify(json).replace(/(\d+\.\d\d\d)\d*/g, ($0,$1) => (Math.round(parseFloat($1) * 1000) / 1000).toString()));

