import React from 'react';

const Introduction = () => (
    <React.Fragment>
        <h3>
            Introduction
        </h3>
        <p>The Homestead Act, passed in May 1862, shaped agricultural and social development in the western United States for many decades. Into the second half of the 1920s, millions of settler households used the law's offer to farm and reside on a parcel of public land for five years, after which they would receive the full property title to the land. A smaller number even used the law in the years after World War II. In the lower forty-eight states, the settlement practice did not officially end until 1976, and in Alaska not until 1986.</p>
        <p>It is difficult to summarize the homesteading experience as a whole, even if one only takes the perspective of the people who claimed land under the law. Settlers took land in very different regions and over a long time, during which new technologies and infrastructure dramatically changed the nature of farm-building. While the first homesteaders in remote areas still struggled to procure building materials and transport crops by wagon, later settlers had access to railroads, better roads, and eventually even cars. Despite these developments, homesteading remained an uncertain business, also in later years. During all phases and in all regions, the number of homesteaders who registered a claim far exceeded the number who succeeded in turning their claim into a final patent. Unsuccessful attempts to build farms were always an integral part of the settlement practice.</p>
        <p>Homesteading was controversial from the beginning. Land reformers had hoped the passage of the free land law would result in a more harmonious society overall, with less harsh class antagonism. But they were quickly disappointed. Most prominently, many lamented the widespread practice of "commuting" homesteads, meaning the early purchase of land parcels by claimants before the expiry of the law's standard five-year residency requirement. Many, including a fair number of lawmakers and later historians, suspected that massive fraud was hiding behind this practice. Instead of supporting the agrarian, Jeffersonian ideal of a society of independent farmers, the Homestead Act seemed to unleash a fierce competition for land to resell, in which influential speculators were coming out on top.</p>
        <p>Historians of the neo-progressive school around Paul W. Gates, which dominated the field from the 1930s to the 1970s, found truth in these complaints. In recent years, however, historians have questioned some of these assumptions. In addition, researchers have also gone beyond measuring the practice of homesteading against its ideals. Instead, studies ask the following questions: To what extent have homesteaders contributed to and benefited from the dispossession and marginalization of Indigenous peoples? Was the opportunity of obtaining land in practice available to all citizens, including non-whites? Or did the land donation program contribute to the existing racial wealth gap by effectively (if not by law) limiting the land to white claimants? How did the law affect the division of labor and the position of women in settler households? What ecological implications did homestead settlements have in different contexts?</p>

        <h3>Mapping homesteading</h3>
        <p>This map offers a new view of the history of homesteading in the first fifty years following the adoption of the Homestead Act. Mapping the General Land Office's internal statistics from local land offices for the entire period from 1863 to 1912, the map provides a granular view of homestead settlements. Previously, statistics were only available for the state level, covering a shorter period, and were compiled in inconsistent ways. The map uses newly digitized diagrams of local land districts that the General Land Office had prepared for a newer published illustrated history to visualize the new statistics. By going below the state level, the map enables a more intricate view of where homesteaders claimed land—and how many claims were converted to full property titles by residency or early purchase (“commutations”).</p>
        <p>The map shows previously unknown patterns in the data, such as local land rushes, which tend to get lost in state-level data. The map also reveals locally very distinct patterns of perfecting claims by commutation instead of residency—which may add to the understanding of controversies surrounding the practice. There are also some larger discoveries in this map; for example, the relatively large number of original and final homesteads in the Deep South states of Alabama, Arkansas, Florida, Louisiana, and Mississippi. Little is known about how homesteading worked in the Jim Crow South, who could use the law, and how it affected social relations under Jim Crow. There has also been little research on homesteading in the Great Lakes region. Beyond making these and other patterns visible, the map also allows for contextualizing qualitative sources, for example, by showing to what extent they corresponded to general patterns—or contradicted them.</p>
        <p>Our map allows for re-examining many different research questions, both old and new. A specific purpose of the map is however to show how homesteaders contributed to and benefited from the dispossession of Indigenous nations. To serve this purpose, we have added another data category to the map: frontier clashes in the "public land" states, that is to say, all the western states except Texas (where the Homestead Act did not apply). These event data show a temporal overlap in the claims between Indigenous people and homesteaders who built farms on previously Indigenous lands. In later years, when the U.S. government carved up reservations into allotments for individual Indigenous households under the 1887 Allotment Act (also known as the Dawes Act), there were also the "homesteads on Indian land." These were claims on the unallotted or "surplus lands" of Indian reservations. In different ways—and with vastly different consequences—homesteading contributed to the marginalization of Indigenous peoples through the entire era covered by this map (for more on this, see the text "Homesteading and Indigenous Dispossession").</p>

        <h3>Selected Literature</h3>
        <ul>
            <li>Dick, Everett. <cite>The Lure of the Land: A Social History of the Public Lands from the Articles of Confederation to the New Deal</cite>. Lincoln, NE: University of Nebraska Press, 1970, pp. 138-159.</li>
            <li>Eckstrom, Mikal Brotnov, and Richard Edwards. “Staking Their Claim: DeWitty and Black Homesteaders in Nebraska.” <cite>Great Plains Quarterly</cite> 38, no. 3 (2018): 295–317.</li>
            <li>Edwards, Richard. “To Commute or Not Commute, the Homesteader’s Dilemma”. <cite>Great Plains Quarterly</cite> 38, No. 2 (2018): 129–50. </li>
            <li>Edwards, Richard, Jacob K. Friefeld, und Rebecca S. Wingo. <cite>Homesteading the Plains: Toward a New History</cite>. Lincoln, NE: University of Nebraska Press, 2017.</li>
            <li>Edwards, Richard, Jacob K. Friefeld, und Mikal Brotnov Eckstrom. “‘Canaan on the Prairie’: New Evidence on the Number of African American Homesteaders in the Great Plains”. <cite>Great Plains Quarterly</cite> 39, No. 3 (2019): 223–41.</li>
            <li>Friefeld, Jacob K., Mikal Brotnov Eckstrom, und Richard Edwards. “African American Homesteader “Colonies” in the Settling of the Great Plains”. <cite>Great Plains Quarterly</cite> 39, No. 1 (2019): 11–37.</li>
            <li>Gates, Paul W. <cite>History of Public Land Law Development</cite>. Washington DC: US Government Printing Office, 1968, pp. 387-462.</li>
            <li>Gates, Paul W. “The Homestead Law in an Incongruous Land System”. <cite>American Historical Review</cite> 41, No. 4 (1936): 652–81.</li>
            <li>Gregg, Sara M. “Imagining Opportunity: The 1909 Enlarged Homestead Act and the Promise of the Public Domain”. <cite>Western Historical Quarterly</cite> 50, No. 3 (2019): 257–79.</li>
            <li>Gregg, Sara M. “American Land Rush: “A Lonely Homesteader” Searches for Security in the Montana Homestead Boom”. Environment & Society Portal, December 15, 2020. http://www.environmentandsociety.org/exhibitions/american-land-rush.</li>
            <li>Landon, George Cooke. “The Homestead Act: Attitudes and Reactions”. PhD dissertation, George Washington University, 1964.</li>
            <li>Okada, Yasuo. Public Lands and Pioneer Farmers: Gage County, Nebraska, 1850-1900. New York: Arno Press, 1978.</li>
        </ul>
    </React.Fragment>
);

export default Introduction;
