import React from 'react';
import IndianCountryMap from '../IndianCountryMap/Index';
import OpenReservationsMap from '../OpenReservationsMap/Index';

const IndigenousDispossession = () => (
    <React.Fragment>
        <h3>Homesteading and Indigenous Dispossession</h3>

        <p>Did homestead settlers benefit from Indigenous land dispossession? To what extent did they cause it? One can examine these multifaceted questions at more general as well as concrete levels.</p>
        <p>On a general level, it is evident that the Homestead Act’s offer of free land was only possible because the U.S. government had through coerced treaties, threats, and force evicted Indigenous nations from their ancestral homelands. The “public land” offered for distribution were only available because Indigenous nations had been removed to small reservations. When Congress passed the Homestead Act in May 1862, most of the area where homesteaders in the following decades would claim land was still “Indian Country,” even according to the U.S. government’s legal understanding. The fact that these lands became accessible to settlers was a clear result of the expulsion of the previous Indigenous inhabitants.</p>
        <IndianCountryMap />
        <p>However, this general statement has little to say about the extent to which homesteaders not only benefitted from but also drove the expulsion itself. In addition to claimants under the Homestead Act, many other groups, ranging from miners and cattle ranchers to railroad companies and land speculators, sought to exploit the resources and lands previously taken from Indigenous nations. Homesteaders are difficult to isolate as a specific group in this coalition of white interests. In addition, the chronological overlap between homesteading and Indigenous removal in the Great Plains and the Mountain States is, by itself, no more than a fundamental, broad linkage. The period between the removal of the Indigenous nations from their lands and the onset of homestead booms was sometimes not just years but decades. </p>
        <p>However, our map also documents a more direct overlap of dispossession and homestead settlements in the 1860s and 1870s. The embedded event data on frontier clashes (which is far from complete) shows that homesteaders advanced into regions that were still contested, for example, in Nebraska and Kansas. This should have been impossible if one goes by the letter of the Homestead Act because the law stipulated that settlers could only register claims to land for which the U.S. government had previously settled all Indigenous claims. How did it come about that there was still fighting with the Cheyenne and Arapaho in the homesteading regions in Nebraska and Kansas? Under the October 1867 Medicine Lodge Treaty, Cheyenne and Arapaho leaders signed an agreement that—according to the verbal assurances of the government’s principal spokesperson, Missouri senator John B. Henderson—would allow them to continue hunting between the Arkansas and South Platte rivers. However, the treaty forwarded to Washington by the commission led by Henderson had no such provision and instead implemented the Indigenous nations’ removal to a reservation. As a result of Henderson’s trickery, western Nebraska and Kansas were declared “public land,” therefore becoming open to homesteaders. The Cheyenne and Arapaho still considered these lands their unceded homelands—which they sought to defend by force against incoming land claimants.</p>
        <p>The case of the Cheyenne and Arapahoe may be a special one that sticks out as a particularly egregious case of fraud that led to some of the bloodiest clashes between Indigenous people and incoming homesteaders. But Henderson’s deceitful negotiation tactics highlight a general feature of the land cessions that preceded the opening of regions to homesteaders: these were not consensual agreements but extorted treaties, often obtained under false conditions. From 1871 onward, the U.S. government even relied entirely on executive orders issued by the president on a unilateral basis. Because of this self-serving practice that effectively brushed aside Indigenous claims to ownership, lands were declared “public” and open for settlement even though Indigenous nations were unwilling to give up their lands and were quite capable of resisting white encroachments. Numerous clashes in the homesteading regions of the 1860s and 1870s indicate this on our map.</p>
        <p>At the same time, the map shows that from the 1860s to 1880s, many clashes between Indigenous people and the U.S. Army or U.S. civilians took place far from the central homesteading regions, especially in the Southwest and the Far West. Therefore, it would be hard to present an argument in the style of new economic history that frontier violence in all of the West was entirely a function of homesteaders moving into a region. The army’s expansive operations and civilian frontier pursuits other than homesteading were more critical in these regions. That being said, our map documents an overlap between homesteading and ongoing frontier fights in some areas throughout the 1860s and 1870s. It was not an invention of popular culture that homestead farm-builders and Indigenous peoples clashed directly over control of the land.</p>
        <p>In addition to these violent clashes of the first decades, beginning in fiscal year 1890, our map documents another direct link between homesteading and Indigenous dispossession. In 1889, the U.S. government opened to homesteaders the Great Sioux Reservation, which extended across the Dakotas, the Ponca Reservation in Nebraska, and the first reservations in the western Indian Territory (now Oklahoma). These were reservations that, according to the original treaties, were supposed to belong to Indigenous nations permanently. In the western Indian Territory, one nation after another was forced to surrender their reservation, after which the areas were opened to settlers as “public land.” </p>
        <p>On the Great Sioux Reservation and the smaller Ponca Reservation in Nebraska, the U.S. government introduced a novel legal instrument: the “homesteads on Indian land.” Instead of forcing Indigenous nations to cede their title, the government assumed the role of a trustee for these nations’ lands. Officially for the nations’ benefit, lands were then opened to homesteaders who had to pay an extra, albeit generally low, purchase price per acre. The U.S. government administered the resulting proceeds in trust for the affected Indigenous nations. As a legal construct, this practice was different from the previous way of opening “Indian land” to U.S. citizens. In practice, however, these privatization policies were frequently put in place under tremendous pressure from the government. And representatives from affected nations pointed out that the arrangement hardly allowed them to profit from land sales proceeds.</p>
        <OpenReservationsMap />
        <p>Both the Great Sioux Reservation and the western parts of the Indian Territory were opened to homestead settlers. “Regular” land sales to purchasers who would not reside on the purchased land were not initially allowed in these areas. This means that the opening and sale of these reservation lands were organized to benefit homesteaders specifically.</p>
        <p>Beginning in the 1890s, the “homesteads on Indian land” contributed significantly to numerous nations' massive communal land losses. Under the 1887 Allotment Act (also known as the Dawes Act), private parcels were carved out from communal reservation lands for tribal members. The remaining parts of reservations were opened to homesteaders as “surplus land.” In exchange for the payment of fees, which the U.S. government took in trust, homesteaders pushed into the last remaining refuges of Indigenous nations.</p>
        <p>In most published statistics, the “homesteads on Indian land” are included in the total of all homesteads. Our map shows the extent of this practice and its specific location. The relationship between the predominantly white settlers who moved onto reservations and the remaining Indigenous nations may have been less openly violent and antagonistic than the Indigenous-homesteader confrontations from the 1860s to 1870s. However, what is clear is that, over the years, homesteading on reservations severely eroded the communal land base of the affected nations. By the time the 1934 Indian Reorganization Act ended this practice, the remaining tribal land base had been radically reduced. In some places, the legal status of reservations as separate Indigenous polities also came into question after reservations in whole or in part had become settled by non-Indigenous majorities.</p>

        <h3>Selected Literature</h3>
        <ul>
            <li>Campbell, Susan D. “Reservations: The Surplus Lands Acts and the Question of Reservation Disestablishment”. <cite>American Indian Law Review</cite> 12, No. 1 (1984): 57–99.</li>
            <li>Edwards, Richard, Jacob K. Friefeld, und Rebecca S. Wingo. <cite>Homesteading the Plains: Toward a New History</cite>.</li>
            <li>Frymer, Paul. B<cite>uilding an American Empire: The Era of Territorial and Political Expansion</cite>. Princeton, NJ: Princeton University Press, 2017.</li>
            <li>Hansen, Karen, and Mignon Duffy. “Mapping the Dispossession: Scandinavian Homesteading at Fort Totten, 1900-1930”. Great Plains Research: A Journal of Natural and Social Sciences 18, No. 1 (2008): 67–80.</li>
            <li>Hansen, Karen V. <cite>Encounter on the Great Plains: Scandinavian Settlers and the Dispossession of Dakota Indians</cite>, 1890-1930. New York: Oxford University Press, 2013.</li>
            <li>Monnett, John H. “Reimagining Transitional Kansas Landscapes: Environment and Violence”. <cite>Kansas History</cite> 34, No. 4 (Winter 2011): 258–79.</li>
            <li>Wilm, Julius. “‘The Indians must yield’: Antebellum Free Land, the Homestead Act, and the Displacement of Native Peoples”. <cite>Bulletin of the German Historical Institute</cite>, No. 67 (Fall 2020): 17–39.</li>
        </ul>
    </React.Fragment>
);

export default IndigenousDispossession;
